name = "traffic-tracker"
main = "src/index.ts"
compatibility_date = "2025-09-15"
account_id = "6034f1c5d23e5503f6573740480cf0d6"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1.0

[[routes]]
pattern = "hirefrank.com/traffic*"
zone_name = "hirefrank.com"

[[routes]]
pattern = "www.hirefrank.com/traffic*"
zone_name = "hirefrank.com"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "traffic-tracker"
database_id = "54e9edee-507a-4171-ab4f-ab2f06a19d5c"

[vars]
START_HOUR = "6"
END_HOUR = "21"
TIMEZONE = "America/New_York"
